/*
 * This Java source file was generated by the Gradle 'init' task.
 * Braxton Soto CS 2263
 */
package edu.isu.cs.cs2263;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

import javafx.geometry.Pos;
import javafx.scene.Scene;
import javafx.scene.control.Button;
import javafx.scene.control.Label;
import javafx.scene.control.ListView;
import javafx.scene.control.TextArea;
import javafx.scene.layout.Pane;
import javafx.scene.layout.VBox;
import javafx.scene.paint.Color;
import javafx.scene.text.Font;
import javafx.scene.text.Text;
import javafx.stage.Stage;
import javafx.application.Application;


public class App extends Application{
    List<Student> studentList = new ArrayList<>();
    @Override
    public void start(Stage primaryStage) throws IOException {
        IOManager.writeData();
        primaryStage.setTitle("Course View");
        primaryStage.setWidth(600);
        primaryStage.setHeight(300);
        Pane pane = new Pane();

        Button button = new Button ("Load Data");
        button.setLayoutX(475);
        button.setLayoutY(225);
        pane.getChildren().add(button);

        Text studentHeader = new Text();
        studentHeader.setText("Students");
        studentHeader.setFont(Font.font("Arial"));
        studentHeader.setFill(Color.BLACK);
        studentHeader.setX(25);
        studentHeader.setY(25);
        pane.getChildren().add(studentHeader);

        Text courseHeader = new Text();
        courseHeader.setText("Courses");
        courseHeader.setFont(Font.font("Arial"));
        courseHeader.setFill(Color.BLACK);
        courseHeader.setX(300);
        courseHeader.setY(25);
        pane.getChildren().add(courseHeader);

        Text isTaking = new Text();
        isTaking.setText("is taking");
        isTaking.setFont(Font.font("Arial"));
        isTaking.setFill(Color.BLACK);
        isTaking.setX(225);
        isTaking.setY(125);
        pane.getChildren().add(isTaking);

        ListView studentArea = new ListView();
        studentArea.setVisible(true);
        studentArea.setLayoutY(35);
        studentArea.setLayoutX(25);
        studentArea.setMaxSize(175, 175);


        pane.getChildren().add(studentArea);

        ListView courseArea = new ListView();
        courseArea.setVisible(true);
        courseArea.setLayoutY(35);
        courseArea.setLayoutX(300);
        courseArea.setMaxSize(500, 175);
        pane.getChildren().add(courseArea);


        Scene scene = new Scene(pane);
        primaryStage.setScene(scene);

        primaryStage.show();
        button.setOnAction(actionEvent ->  {
            try {
                studentArea.getItems().clear();
                studentList = IOManager.readData();
                for (int i = 0; i < studentList.size(); i++ ){
                studentArea.getItems().add(studentList.get(i));
                }
            } catch (FileNotFoundException e) {
                e.printStackTrace();
            }
        });
       studentArea.setOnMouseClicked(actionEvent -> {
           courseArea.getItems().clear();
           List<Course> courseList = new ArrayList<>();
               courseList = studentList.get(studentArea.getSelectionModel().getSelectedIndex()).getAllCourses();
           for(int i = 0; i < courseList.size(); i++){
               courseArea.getItems().add(courseList.get(i));
           }
       });
    }
    public static void main(String[] args) throws IOException {
    Application.launch(args);
    }

}
